mPodroznik/Controllers/BusController/BusRouteController.cs
using AutoMapper;
using mPodroznik.Domain.Entities;
using mPodroznik.HelperClass.ViewModel;
using mPodroznik.ViewModel;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace mPodroznik.Controllers.BusController
{
    public class BusRouteController : Controller
    {
        ViewModelRepozytory repo = new ViewModelRepozytory();
        private static List<BusStopViewModel> _busStopsVMList;
        private static int _busStopID;
        private static BusStopViewModel _busStopVM;
        private BusContex db = new BusContex();


        public ActionResult ShowRouteTable(BusViewModel busNum)
        {
            if (busNum.BusNumber != null)
            {
                var busList = repo.GetBusListViewModel();
                var buses = busList.Where(b => b.BusNumber == busNum.BusNumber).FirstOrDefault();
                _busStopsVMList = buses.BusStops;
            }
            var orderedBusStops = _busStopsVMList.OrderBy(x => x.BusStopOrder).ToArray();
            return View(orderedBusStops);
        }
        public ActionResult ShowRouteMap(BusViewModel busNum)
        {
            var busList = repo.GetBusListViewModel();
            var buses = busList.Where(b => b.BusNumber == busNum.BusNumber).FirstOrDefault();
            _busStopsVMList = buses.BusStops;
            var orderedBusStops = _busStopsVMList.OrderBy(x => x.BusStopOrder).ToArray();
            return View(orderedBusStops);

        }

        // GET: Authors/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            _busStopID = (int)id;
            id--;

            int countBusStops = _busStopsVMList.Count;
            if (id > countBusStops)
            {
                var minId = _busStopsVMList.ElementAt(0);
                id = id - (minId.ID - 1);
            }
            var busStopVM = _busStopsVMList.ElementAt((int)id);
            if (busStopVM == null)
            {
                return HttpNotFound();
            }

            return View("Edit", busStopVM);
        }
        // POST: Authors/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BusStopViewModel busStopVM)
        {
            if (ModelState.IsValid)
            {
                var bus = db.Buses.FirstOrDefault(x => x.ID == busStopVM.BusID);
                var busStop = bus.BusStops.FirstOrDefault(x => x.ID == busStopVM.ID);
                Mapper.Map(busStopVM, busStop);

                //in case there was a change in the busStopOrder                
                var busStopID = _busStopsVMList.FirstOrDefault(x => x.ID == _busStopID);
                if (busStopID.BusStopOrder != busStopVM.BusStopOrder)
                {
                    var busStopsToChange = bus.BusStops.Where(x => x.BusStopOrder >= busStopVM.BusStopOrder).ToList();
                    foreach (var stop in busStopsToChange)
                    {
                        if (stop.BusStopName == busStopVM.BusStopName)
                        {
                            continue;
                        }
                        ++stop.BusStopOrder;
                    }
                }

                //add in case busId changes//

                db.SaveChanges();
                var newBusList = repo.GetBusesFromDB();
                var newBus = newBusList.Where(x => x.BusNumber == busStopVM.BusID.ToString()).FirstOrDefault();

                return RedirectToAction("ShowRouteTable", newBus);
            }
            return View(busStopVM);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            _busStopID = (int)id;
            id--;

            int countBusStops = _busStopsVMList.Count;
            if (id > countBusStops)
            {
                var minId = _busStopsVMList.ElementAt(0);
                id = id - (minId.ID - 1);
            }
            _busStopVM = _busStopsVMList.ElementAt((int)id);
            if (_busStopVM == null)
            {
                return HttpNotFound();
            }

            return View("Delete", _busStopVM);
        }

        // POST: Authors/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete()
        {
            var bus = db.Buses.FirstOrDefault(x => x.ID == _busStopVM.BusID);
            var busStop = bus.BusStops.FirstOrDefault(x => x.ID == _busStopVM.ID);
            bus.BusStops.Remove(busStop);

            var busStopsToChange = bus.BusStops.Where(x => x.BusStopOrder >= _busStopVM.BusStopOrder).ToList();
            foreach (var stop in busStopsToChange)
            {
                if (stop.BusStopName == _busStopVM.BusStopName)
                {
                    continue;
                }
                --stop.BusStopOrder;
            }

            db.SaveChanges();
            var newBusList = repo.GetBusesFromDB();
            var newBus = newBusList.Where(x => x.BusNumber == _busStopVM.BusID.ToString()).FirstOrDefault();

            return RedirectToAction("ShowRouteTable", newBus);
        }
    }
}

mPodroznik/Views/BusRoute/Delete.cshtml
@model mPodroznik.ViewModel.BusStopViewModel
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div>
    <h2>Usunięcie przystanku</h2>
    @using (Html.BeginForm("Delete", "BusRoute", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Przystanek Autobusowy</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2">Linia nr:</label>
                <label class="col-md-10">@Model.BusID</label>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Numer przystanku:</label>
                <label class="col-md-10">@Model.BusStopOrder</label>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Nazwa przystanku:</label>
                <label class="col-md-10">@Model.BusStopName</label>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Szerokosc geofraficzna:</label>
                <label class="col-md-10" >@Model.GPSLat</label>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Dlugosc geograficzna:</label>
                <label class="col-md-10">@Model.GPSLong</label>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Usuń" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("Powrot do Listy", "ShowRouteTable")
</div>


@*<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">Usuniecie przystanku</h4>
            </div>
            <div class="modal-body">
                <h3>Are you sure you want to delete this author?</h3>
                <div>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.BusID)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.BusStopName)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.BusStopOrder)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.GPSLat)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.GPSLong)
                        </dt>
                    </dl>
                </div>
                <div class="modal-footer">
                    @using (Html.BeginForm("Delete", "Authors", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-actions no-color text-center"
                             data-bind="visible: !sending()">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            <button type="button" class="btn btn-default"
                                    data-dismiss="modal">
                                Close
                            </button>
                        </div>
                        <div class="progress" data-bind="visible: sending">
                            <div class="progress-bar progress-bar-info progress-bar-striped active"
                                 role="progressbar" aria-valuenow="100"
                                 aria-valuemin="0" aria-valuemax="100"
                                 style="width: 100%">
                                <span class="sr-only"></span>
                            </div>
                        </div>
                    }
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</div>*@

mPodroznik/Views/BusRoute/Edit.cshtml
@model mPodroznik.ViewModel.BusStopViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h2>Edycja</h2>
    @using (Html.BeginForm("Edit", "BusRoute", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Przystanek Autobusowy</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2">Linia nr</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BusID, new
                    {
                        htmlAttributes = new
                        {
                            @class = "form-control",
                            data_bind = "value: busStop.busId"
                        }
                    })
                    @Html.ValidationMessageFor(model => model.BusID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Numer przystanku</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BusStopOrder, new
                    {
                        htmlAttributes = new
                        {
                            @class = "form-control",
                            data_bind = "value: busStop.busStopOrder"
                        }
                    })
                    @Html.ValidationMessageFor(model => model.BusStopOrder, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Nazwa przystanku</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BusStopName, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       data_bind = "value: busStop.busStopName"
                   }
               })
                    @Html.ValidationMessageFor(model => model.BusStopName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Szerokosc geofraficzna</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GPSLat, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       data_bind = "value: busStop.gpsLat"
                   }
               })
                    @Html.ValidationMessageFor(model => model.GPSLat, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Dlugosc geograficzna</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GPSLong, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       data_bind = "value: busStop.gpsLng"
                   }
               })
                    @Html.ValidationMessageFor(model => model.GPSLong, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Edytuj" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("Powrot do Listy", "ShowRouteTable", Model)
</div>
@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval", "/Scripts/ViewModels/BusStopViewModel.js")*@
    <script src="~/scripts/jquery.validate.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/scripts/ViewModels/BusStopViewModel.js"></script>
    <script>
        var viewModel = new BusStopViewModel(@Html.HtmlConvertToJson(Model));
        ko.applyBindings(viewModel);
    </script>
}

mPodroznik/Views/BusRoute/ShowRoute.cshtml
@model IEnumerable<mPodroznik.ViewModel.BusStopViewModel>

@{
    ViewBag.Title = "Trasa";
}

<h2>Linia nr: @Model.Select(b => b.BusID).FirstOrDefault()</h2>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>nr</th>
                <th>Przystanek</th>
            </tr>
        </thead>
        <tbody>
            @{int i = 0;}
            @foreach (var busStop in Model)
            {                
                <tr>
                    <td>@(1 + i)</td>
                    <td>@busStop.Name</td>
                </tr>
                i++;
            }
        </tbody>
    </table>
</div>

mPodroznik/Views/BusRoute/ShowRouteMap.cshtml
@model IEnumerable<mPodroznik.ViewModel.BusStopViewModel>
@{
    ViewBag.Title = "ShowRouteMap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<head>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false">
    </script>
</head>*@
<h2>Linia nr: @Model.Select(b => b.BusID).FirstOrDefault()</h2>

<div>
    <div id="googleMap" style="width:1024px;height:800px;" align="center"></div>
    @section Scripts{
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false">
    </script>
    @Scripts.Render("~/Scripts/Aplication/map.js")
    <script>
        var viewModel = new ViewModel(@Html.HtmlConvertToJson(Model));
        ko.applyBindings(viewModel);
    </script>
        @*<script>
            function ViewModel(busStops) {
                var self = this;

                self.busStops = busStops;
            };
            var viewModel = new ViewModel(@Html.HtmlConvertToJson(Model));

            var myCenter = new google.maps.LatLng(49.82, 19.0240);
            function initialize() {
                var mapProp = {
                    center: myCenter,
                    zoom: 12,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };

                var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);

                var path = [];
                for (var i = 0; i < viewModel.busStops.length; i++) {
                    
                    var busStop = new google.maps.LatLng(viewModel.busStops[i].gpsLat, viewModel.busStops[i].gpsLng);
                    var marker = new google.maps.Marker({
                        position: busStop,                        
                    });
                    path.push(busStop);

                    marker.setMap(map);
                }

                var busPath = new google.maps.Polyline({
                    path: path,
                    strokeColor: "#0000FF",
                    strokeOpacity: 0.8,
                    strokeWeight: 2

                });
                busPath.setMap(map);
            }

            google.maps.event.addDomListener(window, 'load', initialize);
        </script>*@
        
    }
</div>

mPodroznik/Views/BusRoute/ShowRouteTable.cshtml
@model IEnumerable<mPodroznik.ViewModel.BusStopViewModel>

@{
    ViewBag.Title = "Trasa";
}

<h2>Linia nr: @Model.Select(b => b.BusID).FirstOrDefault()</h2>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Przystanek numer</th>
                <th>Przystanek</th>
                <th>Szerokosc</th>
                <th>Dlugosc</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: busStops">
            <tr>
                <td data-bind="text: busStopOrder"></td>
                <td data-bind="text: busStopName"></td>
                <td data-bind="text: gpsLat"></td>
                <td data-bind="text: gpsLng"></td>
                <td>
                    <a data-bind="attr: {href: '@Url.Action("Edit")/' + id}" class="btn btn-primary">Edytuj</a>
                    <a data-bind="attr: {href: '@Url.Action("Delete")/' + id}" class="btn btn-danger">Usun</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
@section Scripts {
    @Scripts.Render("~/Scripts/Aplication/busStops.js")
    <script>
        var viewModel = new ViewModel(@Html.HtmlConvertToJson(Model));
        ko.applyBindings(viewModel);
    </script>
}